### PR TITLE
fix(docker): Shrink docker image size

### PR DESCRIPTION
**Pull request by jbuck**
The docker image is currently **819.5 MB**. By switching to alpine linux we can reduce the size of the image to **122.8 MB**. By splitting the docker image into a production-only image we can shrink it down to **68.04 MB**.

### CODE REVIEW

**Comment by jbuck** [comment]
Note to self: need to change the jenkins v2 run command

**Comment by vladikoff** [comment]
from mtg: what is this blocked on?

**Comment by jbuck** [comment]
@vladikoff nothing!

r? anyone

**Comment by vladikoff** [comment]
alpine linux it is!

**Pull request merged**
