### PR TITLE
chore(nodejs): Upgrade to Node.js v4.6.2

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by vladikoff** [comment]
```

$ docker build -f Dockerfile-build -t app:build .00:03config
Exit code: 1
docker build -f Dockerfile-build -t app:build .
Sending build context to Docker daemon 1.056 MB


Step 0 : FROM node:4.6.2
Pulling repository docker.io/library/node
Tag 4.6.2 not found in repository docker.io/library/node

docker build -f Dockerfile-build -t app:build . returned exit code 1

Action failed: docker build -f Dockerfile-build -t app:build .
```

**Comment by jrgm** [comment]
Fresh meat.

**Comment by jbuck** [comment]
turns out node 4.6.2 was *just* released so the new docker images are not available yet. We'll land #218 and then tag 73.1 off that

**Comment by vladikoff** [comment]
Needs rebase @jbuck  🍊

**Comment by vladikoff** [comment]
blocked by no docker image for 4.6.2

**Comment by jbuck** [comment]
Rebased, but still no docker image for 4.6.2 available

**Comment by jbuck** [comment]
They finally added the docker image

**Pull request merged**
