### PR TITLE
fix(avatars): add configuration to adjust avatar upload size

### LINKED ISSUE #158: Allow configuring maximum avatar upload size
Blocks #148

### PR DESCRIPTION
**Pull request by seanmonstar**
Closes #158

r? @jrgm

### CODE REVIEW

**Comment by seanmonstar** [comment]
Besides test failures, I'm thinking of changing this to be all config values, so if we wish to tweak it in production, it doesn't require new commits.

**Comment by rfk** [comment]
FWIW, LGTM

**Comment by vladikoff** [comment]
Needs rebase :scream:

**Comment by seanmonstar** [comment]
rebased

**Pull request merged**
