### PR TITLE
chore(release): bump version with 'grunt version'

### LINKED ISSUE #73: improve `grunt release` to bump version

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #73

### CODE REVIEW

**Comment by vladikoff** [comment]
@vbudhram r?

**Comment by jrgm** [comment]
@vladikoff - I tried this out, but not seeing a changelog entry generated. Is there a changelog task?

**Comment by vbudhram** [comment]
@vladikoff, I concur with @jrgm, changelog is being created but no commits inside, even though there have been several commits since last release?

**Comment by vladikoff** [comment]
@vbudhram updated! try now?

**Comment by jrgm** [comment]
WFM

**Comment by jrgm** [comment]
You have lint failures on tasks/changelog.js. Missing semi-colons :-(

**Comment by vbudhram** [comment]
LGTM 👍 , pending tests, merge at will

**Pull request merged**
