### PR TITLE
revert changes for NODE_ENV=production

### PR DESCRIPTION
**Pull request by jrgm**
Paired with https://github.com/mozilla-services/puppet-config/pull/2179. 

r? - @jbuck

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: ea36ddbd1d6d799657f51a78b3ed51a9c59e0c68
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 84f542b588376239328526357113c692afe44437
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 008eee8de564621869f3dee2f47b014509a89d8d
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/mozilla/fxa-profile-server

---
This message was auto-generated by https://gitcop.com

**Comment by jrgm** [comment]
@GitCop - hmm, do you not understand `git revert`?

**Comment by vladikoff** [comment]
@rfk @jbuck do we need to merge this before cutting the train?

**Comment by jbuck** [comment]
I think we should accept this PR, with an additional commit that removes setting it based on NODE_ENV and setting NODE_ENV to this value.

Why treat NODE_ENV specially? Because a fair number of packages do production optimizations based on whether NODE_ENV === "production". Right now we only set NODE_ENV to one of test, dev, stage, or prod. I suggest we change this identifier to FXA_ENV or something similar, and only set NODE_ENV to production.

Thoughts?

**Comment by jrgm** [comment]
Interesting point, and yet another reason I hate this broken Rails-ish pattern.

I had not previously known that Express would change defaults based on this globally ambiguous setting. Which others?

**Comment by vladikoff** [comment]
from mtg: @jbuck could you add the comment you mentioned and merge?

**Pull request merged**
