### PR TITLE
chore(dependencies): update hapi dependency to 7.5.3

### LINKED ISSUE #86: Update Hapi dep?
See https://github.com/mozilla/fxa-auth-server/pull/853

I think the validate-shrinkwrap task will complain about the "intert" module, iirc.

### PR DESCRIPTION
**Pull request by rfk**
Closes #86

### CODE REVIEW

**Comment by rfk** [comment]
So much churn in npm-shrinkwrap.json, so few blanks given...

**Comment by rfk** [comment]
@vladikoff r?

**Comment by vladikoff** [comment]
Thanks!

**Comment by pdehaan** [comment]
Hooray!

> Running "validate-shrinkwrap" task
/Users/pdehaan/dev/fxa-profile-server_pd/fxa-profile-server/npm-shrinkwrap.json
No vulnerable modules found

**Pull request merged**
