### PR TITLE
feat(test): in load test, add delete after download

### PR DESCRIPTION
**Pull request by jrgm**
This deletes the image after initial upload and successful download. @seanmonstar or @rfk r?

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 68c4ef998acd6cb691266ddc5070610991ec1720
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-profile-server

---
This message was auto-generated by https://gitcop.com

**Comment by jrgm** [comment]
I guess @GitCop doesn't recognize a force push of a `git commit --amend`?

**Comment by rfk** [comment]
LGTM.  Will this skew your load profile by doing far more deletes than we'd actually see in production, and does that matter for the way you're using it?

**Comment by jrgm** [comment]
Yeah, that occurred to me, and I should add an option to not always delete.

**Comment by jrgm** [comment]
Okay, added a `--delete` option.

**Comment by rfk** [comment]
:+1:

**Comment by jrgm** [comment]
Thanks.

**Pull request merged**
