### PR TITLE
fix(traceback): #203 add mock

### LINKED ISSUE #203: Avoid printing error tracebacks on the log for successful test runs
Noticed in the travis logs that this error is thrown in (I think) `should error our on unexpected 400s from auth server`. (But running tests individually doesn't appear to produce the error). 

```
fxa-profile-server.server.ERROR: summary {"code":500,"method":"get","errno":999,"path":"/v1/email",
  "agent":"shot","t":227377,"stack":"Error: error communicating with auth server
    at Request.module.exports.handler [as _callback] (/Users/jrgm/tmp33/fxa-profile-server/lib/routes/email.js:54:22)
    at Request.init.self.callback (/Users/jrgm/tmp33/fxa-profile-server/node_modules/request/request.js:187:22)
    at Request.emit (events.js:98:17)
    at Request.readResponseBody (/Users/jrgm/tmp33/fxa-profile-server/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.Request.onRequestResponse (/Users/jrgm/tmp33/fxa-profile-server/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)"}
```

### PR DESCRIPTION
**Pull request by deeptibaghel**
Fixes #203 : Added  mocks for the log to not output the summary of a 500 for the successful tests.

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: d665567e9edbc8572319b22a90b67fe43a0cc474
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-profile-server

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: d665567e9edbc8572319b22a90b67fe43a0cc474
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-profile-server

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
@deeptibaghel awesome! 👍

**Pull request merged**
