### PR TITLE
feat(hpkp): Add hpkp headers to all requests

### PR DESCRIPTION
**Pull request by vbudhram**
Ref: https://github.com/mozilla/fxa-bugzilla-mirror/issues/179

### CODE REVIEW

**Comment by seanmonstar** [comment]
Blocked on what?

**Comment by vbudhram** [comment]
Woops, should have mention that, blocked on merging initial logic for [hapi-module](https://github.com/vbudhram/hapi-hpkp/pull/1).

**Comment by vladikoff** [comment]
@vbudhram do these just need to be updated to use the new hapi module?

**Comment by vbudhram** [comment]
@vladikoff Yup, was in process of updating, should be ready soon!

**Comment by vbudhram** [comment]
Update project to use the `hapi-hpkp` module. This is the same one that is used in the auth-server. 

@mozilla/fxa-devs r?

**Pull request merged**
